/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBookRouteImport } from './routes/_authenticated/book'
import { Route as AuthenticatedFarmerRouteImport } from './routes/_authenticated/farmer'
import { Route as AuthenticatedOperatorRouteImport } from './routes/_authenticated/operator'
import { Route as AuthenticatedTokenTokenIdRouteImport } from './routes/_authenticated/token.$tokenId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookRoute = AuthenticatedBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFarmerRoute = AuthenticatedFarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperatorRoute = AuthenticatedOperatorRouteImport.update({
  id: '/operator',
  path: '/operator',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTokenTokenIdRoute =
  AuthenticatedTokenTokenIdRouteImport.update({
    id: '/token/$tokenId',
    path: '/token/$tokenId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/book': typeof AuthenticatedBookRoute
  '/farmer': typeof AuthenticatedFarmerRoute
  '/operator': typeof AuthenticatedOperatorRoute
  '/token/$tokenId': typeof AuthenticatedTokenTokenIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/book': typeof AuthenticatedBookRoute
  '/farmer': typeof AuthenticatedFarmerRoute
  '/operator': typeof AuthenticatedOperatorRoute
  '/token/$tokenId': typeof AuthenticatedTokenTokenIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/book': typeof AuthenticatedBookRoute
  '/_authenticated/farmer': typeof AuthenticatedFarmerRoute
  '/_authenticated/operator': typeof AuthenticatedOperatorRoute
  '/_authenticated/token/$tokenId': typeof AuthenticatedTokenTokenIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/book'
    | '/farmer'
    | '/operator'
    | '/token/$tokenId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/book'
    | '/farmer'
    | '/operator'
    | '/token/$tokenId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/book'
    | '/_authenticated/farmer'
    | '/_authenticated/operator'
    | '/_authenticated/token/$tokenId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/book': {
      id: '/_authenticated/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof AuthenticatedBookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/farmer': {
      id: '/_authenticated/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof AuthenticatedFarmerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operator': {
      id: '/_authenticated/operator'
      path: '/operator'
      fullPath: '/operator'
      preLoaderRoute: typeof AuthenticatedOperatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/token/$tokenId': {
      id: '/_authenticated/token/$tokenId'
      path: '/token/$tokenId'
      fullPath: '/token/$tokenId'
      preLoaderRoute: typeof AuthenticatedTokenTokenIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBookRoute: typeof AuthenticatedBookRoute
  AuthenticatedFarmerRoute: typeof AuthenticatedFarmerRoute
  AuthenticatedOperatorRoute: typeof AuthenticatedOperatorRoute
  AuthenticatedTokenTokenIdRoute: typeof AuthenticatedTokenTokenIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBookRoute: AuthenticatedBookRoute,
  AuthenticatedFarmerRoute: AuthenticatedFarmerRoute,
  AuthenticatedOperatorRoute: AuthenticatedOperatorRoute,
  AuthenticatedTokenTokenIdRoute: AuthenticatedTokenTokenIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
